### ISSUE TITLE
 MQTT_GENERIC_BRIDGE only starts after shutdown restart

### ISSUE THREAD

**Issue by EmEiBee** [hexenmeister/MyFHEM#11]
If the entire server or FHEM is restarted using ReReadCFG (ReReadCFG or the entire operating system), the bridge is not started.
After "Shutdown Restart" this is available and works well.

Reproducible on a RaspBerry PI and a XEON, each with the latest Debian Buster

(I haven't been a member of the FHEM forum for some time; cbx.micha bei gmail)

**Comment by hexenmeister** [comment]
rereadcfg has some other problems and should not be used anymore

**Comment by EmEiBee** [comment]
... you probably thought that FHEM has a problem and shouldn't be used anymore ?! That would have been honest at least ^^
FHEM is now something for the self-proclaimed "star developers" who prefer to offend the questioner with problems of common foot folk instead of helping with a solution ...

**Comment by hexenmeister** [comment]
You misunderstand. And you are also offending everyone who is investing their time, not the developers. Do it yourself better, send me a pull request. I'll check it out and check in if it's ok.

Again: Rereadcfg does nothing useful, but causes problems in many places. Use shutdown restart.

**Comment by EmEiBee** [comment]
... I understand that correctly and I do not insult anyone; It is cheeky to assume that, because from my experiences from the FHEM forum it is usually the other way around, and not just with me ... Because even a user can feel offended if he is right from the start Stupidity and ignorance is assumed; if the user had the developer’s level of knowledge, he wouldn’t need to ask and expose himself to the often completely senseless and condescending answers ...

The fact is that most developers (not only at FHEM) don't feel like checking user problems. It is the same here. Because I wrote clearly and unmistakably that this problem not only occurs with a ReRead, but also when the server itself is restarted. You can only get it to run if you perform a shutdown restart at least once, often several times.

**Comment by hexenmeister** [comment]
RereadCfg is NOT a FHEM restart and should no longer be used. I've already written that.
Unfortunately I overlooked the fact that it also happened when the server was restarted. I'm sorry, my English is not perfect and I had very little time.
I restarted my server. Multiple. I never had the problem. No one else has reported this problem.
I have several FHEM instances running with the bridge. None of these have this problem. I can not reproduce it. Your description doesn't help me either. What does "the bridge is not started" mean? I don't know your configuration. I don't see your logs. I don't have a crystal ball.
My experiences in the FHEM forum are very different from yours. I always got help. Could your way of communicating be the reason?
From the second message onwards, your messages contain nothing constructive, but a lot of ridicule and insults. However, I don't feel like spending my time in this discussion.

Have a nice day.

**Comment by EmEiBee** [comment]
(Deutsch besser?)

... da musste ich nun doch lachen ;o) Das Du keine Probleme im FHEM- Forum hast ist klar. Du bist Entwickler und auf dem gleichen oder ähnlichem Niveau wie die anderen so genannten Experten. Aber wenn Du Dir mal die Mühe machst und in den klassischen Bereichen der Anwender schaust, dann wirst auch Du recht schnell feststellen, das Fragende in der Regel mit "lies die CommandRef", "lies Beitrag XY" und ähnlichem angeranzt werden. In den anderen Fällen ist es oft so, das die Experten auf die gestellte Frage gar nicht eingehen sondern vom Thema wegführen mit allerlei Belehrungen und ähnlichem nicht zielführendem Gerede. Das war vor etlichen Wochen auch der Grund, warum ich gegangen bin. Ich hatte einfach keine Lust mehr, bei 9 von 10 Fragen zu langen Debatten genötigt zu werden, die mit dem Problem an sich nichts zu tun hatten.
Ähnliches hast Du hier mit mir auch gemacht: Anstatt auf mein Problem einzugehen hast Du ohne jegliche Begründung darauf hingewiesen, das man ReReadCFG nicht mehr nutzen soll. Davon hatte ich noch nie was gehört und auch in der aktuellen Version ist diese Funktion noch vorhanden. Auch die CommandRef sagt darüber kein Wort. Hat es mein Problem gelöst? Nein, hat es nicht.
>" ...What does "the bridge is not started" mean? I don't know your configuration. I don't see your logs. I don't have a crystal ball. ..." 

Ja, da hast Du recht. Wenn meine Kristalkugel in Reparatur ist, bin ich auch aufgeschmissen ;o) Letztlich aber sind wir zu diesem Punkt gar nicht gekommen (siehe oben)... Wenn von Dir z.B. als Antwort auf meine initiale Frage "... ReReadCFG sollte nicht benutzt werden weil ...blablub... / Steht auch hier und da... / Was genau meinst Du mit startet nicht? ..." oder so was ähnliches gekommen wäre, hätte es sicherlich eine zielführende Kommunikation generiert...

Ich habe ja Verständnis dafür, das die "Experten" keine Lust haben, immer und immer wieder die gleichen Fragen zu beantworten; vollkommen in Ordnung. Aber dann sollten sich diese Experten doch einfach zurück halten und schweigen und jenen das Feld überlassen, die wirklich beim Lösen des angefragten Problems helfen möchten. Und ich spreche davon nicht ohne Erfahrung. Dieses Problem hat fast jedes Forum, wenn es älter und größer wird. Ich habe auch über 10 Jahre ein Fachforum geleitet und wurde zum Schluss immer häufiger von jenen angefeindet, die ich immer öfter darauf hinweisen musste, das ein TE einen Grund hat, eine Frage zu stellen und der TE gefälligst so zu behandeln ist, wie man es vor Jahren als Neuling selbst erwartet hat.

Noch was zur Art meiner Kommunikation: Ich kann echt freundlich und konstruktiv an einem Thema arbeiten. Ich bin schon etwas älter und ebenfalls Entwickler in einem anderen Bereich. Ich verstelle mich aber auch nicht, wenn ich verärgert bin. Das mag sicherlich ein Kritikpunkt sein, aber für andere verbiegen war noch nie mein Fall. Ich vertrage auch konstruktive Kritik und nehme Diese gerne an. Das aber kann ich von anderen oft nicht sagen (schon gar nicht im FHEM- Forum).
In dem Zusammenhang mal schlicht die Frage, was in meinem vorherigen Beitrag denn "lächerlich" oder gar eine "Beleidigung" war? Sehe ich auch nach mehrmaligem Durchlesen nirgends. 
Kann natürlich sein, das meine Kritik als Beleidigung oder als lächerlich empfunden wurde; wenn dem so ist, dann ist diese Kommunikation tatsächlich vollkommen sinnfrei (wie mit allen Personen, die keine Kritik vertragen).

In diesem Sinne trotz allem alles Gute
