### ISSUE TITLE
Experimental keys on scalar is now forbidden Perl 5.28

### ISSUE THREAD

**Issue by CoolTuxNet** [hexenmeister/MyFHEM#12]
Hallo Alexander,

Mit Version 5.28 kommt im Modul 36_GSD folgende Fehlermeldung.
Error:Modul 36_GSD deactivated: Experimental keys on scalar is now forbidden at ./FHEM/36_GSD.pm line 678.

Lösung:
my @readings_keys=keys( %{$dMap->{READINGS}} );

Zeile 674

Grüße
Marko

**Comment by hexenmeister** [comment]
Hallo Marko,

danke für den Hinweis (und vor Allem, dass Du die Lösung gleich mitlieferst :))!
Habe jetzt die Änderung eingecheckt. 
Verwendest Du selbst dieses Modul? Ich selbst habe mittlerweile keine Geräte mehr, die das nutzen.

Viele Grüße
Alexander

**Comment by CoolTuxNet** [comment]
Hallo Alexander,

Ich verwende dieses Modul nicht. Ein User im Forum hatte Probleme damit und ich habe ihm bei der Lösungsfindung geholfen.


Grüße

**Comment by hexenmeister** [comment]
Oha, das ist leider an mir vorbei gegangen. Danke nochmals.
Grüße
Alexander
