### ISSUE TITLE
SD Backup

### ISSUE THREAD

**Issue by Kolbi** [hexenmeister/MyFHEM#5]
Hallo hexenmeister,

ist es möglich das Backup Skript ( https://github.com/hexenmeister/MyFHEM/blob/master/_scripts/sd_backup.sh ) zu optimieren, indem geprüft wird, ob cron, apache2 oder mysql überhaupt vorher liefen?

In meinem Fall würde es apache2 und mysql zwar nicht stoppen (läuft nicht), aber nach dem Backup starten.

Q&D für mich wäre einfach das entfernen der Zeilen... :-)

Shut down some services before starting backup process
41  echo "Stopping some services before backup."
42  sudo service cron stop
43  sudo service apache2 stop
44  sudo service mysql stop

Start services again that where shutdown before backup process
57  echo "Start the stopped services again."
58  sudo service mysql start
59  sudo service apache2 start
60  sudo service cron start

**Comment by hexenmeister** [comment]
Hallo!

Bestimmt kann man das irgendwie prüfen. Ich denke aber, der Aufwand
lohnt sich nicht. Ich würde genau so machen: für jeden konkreten Rechner
einfach ein wenig anpassen :)

Grüße,

Alexander


Am 09.04.2015 um 12:03 schrieb Kolbi:
