### ISSUE TITLE
Notify zu checkCalSummary

### ISSUE THREAD

**Issue by CoolID2** [hexenmeister/MyFHEM#6]
Hallo Hexenmeister,

ich bin gerade auf Deine 99_myUtils.pm gestossen und würde gerne das Script "checkCalSummary" bei mir integrieren.
Könntest Du mir vielleicht dazu Deinen notify-Aufruf schicken? Oder einen kleinen Auszug aus Deiner fhem.cfg?

Wäre Dir sehr zu Dank verpflichtet.

**Comment by hexenmeister** [comment]
Hallo!

Das war ein früherer Versuch, den ich letztendlich nicht weitergeführt
hatte.
Die Konfiguration von damals sah so aus:

define GC Calendar ical url
https://www.google.com/calendar/ical/*********/basic.ics 900
define GC_Abwesend dummy
define GC.notify notify GC { fhem "set GC_Abwesend
".checkCalSummary("GC", "modeStart", "Abwesend") }


Grüße
Alexander

Am 15.01.2017 um 19:25 schrieb CoolID2:

**Comment by CoolID2** [comment]
Hallo,
vielen Dank. Der Punkt vor dem .checkCalSummary war es, der mich zum verzweifeln gebracht hat. 

Du sagst, Du hast den Versuch nicht mehr weiter verfolgt? Hast Du eine bessere Lösung gefunden bzw. umgesetzt?

Grüße
