### ISSUE TITLE
Fix in  42_SYSMON.pm

### ISSUE THREAD

**Issue by s1738berger** [hexenmeister/MyFHEM#7]
Hallo Hexenmeister
in my FHEM-Log in got tons of errors:
`PERL WARNING: Use of uninitialized value $_ in pattern match (m//) at ./FHEM/42_SYSMON.pm line 2854.`

I use the latest version of FHEM and the modules. The version of SYSMON is:
`$Id: 42_SYSMON.pm 14823 2017-07-31 16:53:41Z hexenmeister $`
`my $VERSION = "2.3.2";`

This could be an easy fix to get rid of those messages:
Around line 2852 include **next unless ($_);** in the foreach loop;

`my @iwData = SYSMON_execute($hash, "/sbin/iwconfig $nDef 2>/dev/null");`
`foreach (@iwData) {`
`  next unless ($_);`
`  if($_=~ m/Bit\sRate+(=|:)*(\S*)/) {`
`	$speed=$2;`
`  }`

Would be nice to see that in the next release of SYSMON.
Regards, Stefan

```

**Comment by hexenmeister** [comment]
True, that's better. Thanks for the good preparation. :)
The change comes with the next update.

Best regards,
Alexander
